-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS tb_equipamento
(
    eq_id srial NOT NULL,
    eq_produto integer NOT NULL,
    eq_patrimonio character varying(10),
    eq_serial character varying(15),
    eq_observacao character varying(80),
    CONSTRAINT tb_equip_pkey PRIMARY KEY (eq_id)
);

CREATE TABLE IF NOT EXISTS tb_marca
(
    mc_id serial NOT NULL,
    mc_nome character varying(30) NOT NULL,
    CONSTRAINT tb_marca_pkey PRIMARY KEY (mc_id)
);

CREATE TABLE IF NOT EXISTS movimentacao
(
    mv_id serial NOT NULL,
    "mv_dataHora" time with time zone DEFAULT now(),
    mv_item integer NOT NULL,
    mv_origem character varying(20) NOT NULL,
    mv_destino character varying(20) NOT NULL,
    mv_chamado character varying(10),
    CONSTRAINT tb_movimentacao_pkey PRIMARY KEY (mv_id)
);

CREATE TABLE IF NOT EXISTS tb_produto
(
    pr_id serial NOT NULL,
    pr_marca integer NOT NULL,
    pr_tipo integer NOT NULL,
    pr_modelo character varying(30) NOT NULL,
    pr_descricao character varying(60),
    CONSTRAINT tb_prod_pkey PRIMARY KEY (pr_id)
);

CREATE TABLE IF NOT EXISTS tb_tipo
(
    tp_id serial NOT NULL,
    tp_descricao character varying(30) NOT NULL,
    CONSTRAINT tb_tipo_pkey PRIMARY KEY (tp_id)
);

CREATE TABLE IF NOT EXISTS tb_usuario
(
    us_id serial NOT NULL,
    us_nome character varying(60) NOT NULL,
    us_email character varying(50) NOT NULL,
    us_senha character varying(20) NOT NULL,
    CONSTRAINT tb_usuario_pkey PRIMARY KEY (us_id)
);

ALTER TABLE IF EXISTS tb_equipamento
    ADD CONSTRAINT it_eq FOREIGN KEY (eq_produto)
    REFERENCES public.tb_produto (pr_id) MATCH SIMPLE;


ALTER TABLE IF EXISTS public.tb_movimentacao
    ADD CONSTRAINT mv_it FOREIGN KEY (mv_item)
    REFERENCES public.tb_equipamento (eq_id);


ALTER TABLE IF EXISTS public.tb_produto
    ADD CONSTRAINT eq_mc FOREIGN KEY (pr_marca)
    REFERENCES public.tb_marca (mc_id) MATCH SIMPLE;


ALTER TABLE IF EXISTS public.tb_produto
    ADD CONSTRAINT eq_tp FOREIGN KEY (pr_tipo)
    REFERENCES public.tb_tipo (tp_id) MATCH SIMPLE;

END;